adding react big calendar with faux events week view
RoomEase2018/RoomEase pull request #33
Opened 2018-03-27 03:18 UTC by benprofit

git pull origin calendar
cd frontend
npm start

- needs real events (chores, bills, expenses)

2018-03-27 04:10 UTC, liueric-dev requested changes
clicking on week/month does not work, calendar is incomplete

2018-03-28 16:58 UTC, aidenshih approved these changes
Looks good

2018-03-28 16:59 UTC, aidenshih approved these changes

2018-03-28 18:12 UTC, liueric-dev approved these changes
cool beans

2018-03-28 18:12 UTC, merged